import { defineStore } from 'pinia';
import { computed, ref } from 'vue';
import { TicketingApi } from '../infrastructure/ticketing-api.js';
/**
 * Holds Ticketing Integration application state and orchestrates
 * synchronization and connection flows.
 */
export const useTicketingStore = defineStore('ticketing', () => {

    const ticketingApi = new TicketingApi();

    // --------------------------------------------------------------------
    // State
    // --------------------------------------------------------------------

    /**
     * Ticketing integrations available in the system.
     */
    const ticketingIntegrations = ref([]);

    /**
     * Synchronization logs generated by ticketing integrations.
     */
    const syncLogs = ref([]);

    /**
     * Occupancy information synchronized for shows.
     */
    const showOccupancies = ref([]);

    /**
     * Indicates whether ticketing integrations are being loaded.
     */
    const loadingIntegrations = ref(false);

    /**
     * Indicates whether synchronization information is being loaded.
     */
    const loadingSynchronizations = ref(false);

    /**
     * Stores the last application error.
     */
    const error = ref(null);

    // --------------------------------------------------------------------
    // Computed state
    // --------------------------------------------------------------------

    /**
     * Number of configured ticketing integrations.
     */
    const integrationsCount = computed(
        () => ticketingIntegrations.value.length
    );

    /**
     * Number of currently connected ticketing integrations.
     */
    const connectedIntegrationsCount = computed(
        () =>
            ticketingIntegrations.value.filter(
                integration => integration.isConnected
            ).length
    );

    /**
     * Indicates whether at least one ticketing integration is connected.
     */
    const hasConnectedIntegration = computed(
        () => connectedIntegrationsCount.value > 0
    );

    // --------------------------------------------------------------------
    // Integration queries
    // --------------------------------------------------------------------

    /**
     * Loads ticketing integrations into application state.
     */
    async function loadTicketingIntegrations() {
        loadingIntegrations.value = true;
        error.value = null;

        try {
            ticketingIntegrations.value =
                await ticketingApi.getTicketingIntegrations();
        } catch (err) {
            error.value = err;
        } finally {
            loadingIntegrations.value = false;
        }
    }

    /**
     * Finds a ticketing integration by identifier.
     *
     * @param {number|string} id Integration identifier.
     */
    function getTicketingIntegrationById(id) {
        return ticketingIntegrations.value.find(
            integration => String(integration.id) === String(id)
        );
    }

    // --------------------------------------------------------------------
    // Connection operations
    // --------------------------------------------------------------------

    /**
     * Connects Kinemo with an external ticketing provider.
     *
     * @param {number|string} integrationId Integration identifier.
     */
    async function connect(integrationId) {
        error.value = null;

        try {
            const updatedIntegration =
                await ticketingApi.connect(integrationId);

            replaceIntegration(updatedIntegration);
        } catch (err) {
            error.value = err;
        }
    }

    /**
     * Disconnects an external ticketing integration.
     *
     * @param {number|string} integrationId Integration identifier.
     */
    async function disconnect(integrationId) {
        error.value = null;

        try {
            const updatedIntegration =
                await ticketingApi.disconnect(integrationId);

            replaceIntegration(updatedIntegration);
        } catch (err) {
            error.value = err;
        }
    }

    // --------------------------------------------------------------------
    // Synchronization
    // --------------------------------------------------------------------

    /**
     * Synchronizes ticket sales and occupancy information from
     * the external ticketing provider.
     *
     * @param {number|string} integrationId Integration identifier.
     */
    async function synchronize(integrationId) {
        loadingSynchronizations.value = true;
        error.value = null;

        try {
            const result =
                await ticketingApi.synchronize(integrationId);

            if (result.syncLog) {
                syncLogs.value.push(result.syncLog);
            }

            if (result.showOccupancy) {
                replaceShowOccupancy(result.showOccupancy);
            }

            if (result.integration) {
                replaceIntegration(result.integration);
            }

            return result;
        } catch (err) {
            error.value = err;
            throw err;
        } finally {
            loadingSynchronizations.value = false;
        }
    }

    /**
     * Loads synchronization logs.
     */
    async function loadSyncLogs() {
        error.value = null;

        try {
            syncLogs.value = await ticketingApi.getSyncLogs();
        } catch (err) {
            error.value = err;
        }
    }

    /**
     * Loads synchronized show occupancies.
     */
    async function loadShowOccupancies() {
        error.value = null;

        try {
            showOccupancies.value =
                await ticketingApi.getShowOccupancies();
        } catch (err) {
            error.value = err;
        }
    }

    /**
     * Returns synchronization logs belonging to an integration.
     *
     * @param {number|string} integrationId Integration identifier.
     */
    function getSyncLogsByIntegrationId(integrationId) {
        return syncLogs.value.filter(
            log =>
                String(log.integrationId) ===
                String(integrationId)
        );
    }

    /**
     * Returns the synchronized occupancy for a show.
     *
     * @param {number|string} showId Show identifier.
     */
    function getShowOccupancyByShowId(showId) {
        return showOccupancies.value.find(
            occupancy =>
                String(occupancy.showId) === String(showId)
        );
    }

    // --------------------------------------------------------------------
    // Helpers
    // --------------------------------------------------------------------

    /**
     * Replaces an integration in application state.
     *
     * @param {Object} updatedIntegration Updated integration.
     */
    function replaceIntegration(updatedIntegration) {
        const index = ticketingIntegrations.value.findIndex(
            integration =>
                String(integration.id) ===
                String(updatedIntegration.id)
        );

        if (index !== -1) {
            ticketingIntegrations.value[index] =
                updatedIntegration;
        }
    }

    /**
     * Updates an existing occupancy or adds it if it does not exist.
     *
     * @param {Object} updatedOccupancy Updated occupancy.
     */
    function replaceShowOccupancy(updatedOccupancy) {
        const index = showOccupancies.value.findIndex(
            occupancy =>
                String(occupancy.showId) ===
                String(updatedOccupancy.showId)
        );

        if (index !== -1) {
            showOccupancies.value[index] =
                updatedOccupancy;
        } else {
            showOccupancies.value.push(updatedOccupancy);
        }
    }

    return {
        // State
        ticketingIntegrations,
        syncLogs,
        showOccupancies,
        loadingIntegrations,
        loadingSynchronizations,
        error,

        // Computed
        integrationsCount,
        connectedIntegrationsCount,
        hasConnectedIntegration,

        // Queries
        loadTicketingIntegrations,
        getTicketingIntegrationById,

        // Connection
        connect,
        disconnect,

        // Synchronization
        synchronize,
        loadSyncLogs,
        loadShowOccupancies,
        getSyncLogsByIntegrationId,
        getShowOccupancyByShowId,
    };
});